### ISSUE TITLE
Implement 'Play All' and 'Shuffle' controls

### ISSUE THREAD

**Issue by ericzelenka** [Azero123/JW-Broadcasting#16]
Implement 'Play All' and 'Shuffle' controls for Sing to Jehovah and Kingdom Melodies.

**Comment by ericzelenka** [comment]
Implement 'Play All' and 'Shuffle' controls for Sing to Jehovah and Kingdom Melodies.

**Comment by Azero123** [comment]
Likely to incorporate this into MOD over the break.

**Comment by Azero123** [comment]
Closing, refer to: "FR P3 Media on Demand" issue for this.
