### ISSUE TITLE
Investigation: New UI design for 'Audio' tab

### ISSUE THREAD

**Issue by ericzelenka** [Azero123/JW-Broadcasting#18]
The current design of the 'Audio' tab doesn't take into account unique UI needs of finding and playing music. 
- Large quantity of items, lots to swipe through
- No 'Play All' or 'Shuffle' buttons

Investigate new UI designs and layouts.

**Comment by Azero123** [comment]
WIP
Code for implementing the tab has been added and I will be working on it over the break.

**Comment by Azero123** [comment]
Closing, refer to: "FR P3 Media on Demand" issue for this.
