### ISSUE TITLE
Add JW Broadcasting logo to top center of Home screen 

### ISSUE THREAD

**Issue by ericzelenka** [Azero123/JW-Broadcasting#26]
Add JW Broadcasting logo to top center of Home screen.

Use the image at: http://tv.jw.org/assets/776a549fe6/images/jw-broadcasting-logo.png

When the Tab bar is down it should completely cover the JW Broadcasting logo.

When you make this change, also all contents on the Home screen down such that 'Latest Videos' is no longer shown on the Home screen by default. With the JW Broadcasting Logo showing (Tab bar hidden), or the Tab bar showing none of the items not the screen should jump around. Only thing that should display without swiping are:

Tab Bar or JW Broadcast logo depending on state
## Featured Items showcase

Streaming
## [Each Streaming channel]

NOTE: Latest Videos should NOT be shown on the Home screen without swiping down.

**Comment by Azero123** [comment]
Closing, implemented.
