### ISSUE TITLE
UITableViewCellStyle for Songs, Dramas and Dramatic Readings

### ISSUE THREAD

**Issue by ericzelenka** [Azero123/JW-Broadcasting#50]
UITableViewCellStyle for Songs should use 'Subtitle' with the subtitle being the song number. (Song length does not need to be displayed.)

UITableViewCellStyle for Dramas should use 'Value1' with the value being the audio recording length (time).

UITableViewCellStyle for Dramatic Readings should use 'Value1' with the value being the audio recording length (time).

**Comment by Azero123** [comment]
Added sub and side titles. Closing.
