### ISSUE TITLE
P3 Add JW logo

### ISSUE THREAD

**Issue by Azero123** [Azero123/JW-Broadcasting#8]
Add the JW logo to the top left of the screen

**Comment by kryptonianson** [comment]
Do you need a graphic for this?

**Comment by Azero123** [comment]
![jw-white-background-blue](https://cloud.githubusercontent.com/assets/14842127/11226290/d789c50e-8d33-11e5-8bca-8393ea889db8.png)
I cropped one of the images you gave me and made this. But if you have time and have another idea go right ahead (:

**Comment by kryptonianson** [comment]
Have a Screenshot?

**Comment by Azero123** [comment]
Ya, didn't know github didn't forward attachments from mail. There you go.

**Comment by kryptonianson** [comment]
And how are you using it?

**Comment by Azero123** [comment]
I haven't got to that yet, on iOS normally you can add tab bar items but not in TVOS. So I have to figure out how other people are doing it.

**Comment by Azero123** [comment]
I may just end up throwing a UIImageView over the tab bar because I am already tracking the tab bars position.

**Comment by Azero123** [comment]
Closed, code completed.
